### ISSUE TITLE
Repository contains non-open resource code

### ISSUE THREAD

**Issue by LamiaHu7** [ADmitriyP/MQB_studies#2]
This is an alert from SAIC VolksWagen:

Your GitHub repository contains SAIC VW related non-open resource code, it is seen as illegal disclosure of the secret information in SAIC VW's intellectual property. **Please delete related codes ASAP.**

Related code: https://github.com/ADmitriyP/VAG_MQB_studies/blob/main/MIB%20Desay%20869%20CRS%203.0/Language/Chinese.xml

**Comment by ADmitriyP** [comment]
Hello, LamiaHu7!

The file with the extension .xml contains only a description of the language interface and is obtained by simply unpacking the archive.the bin of the firmware update file for the Desay 869 device, **not SAIC 869**!. Any unzipping tool allows you to access these language files.xml files.  Please note that there is also no information about the company's electronic certificates here.

Also, the **SAIC 869** firmware update file is protected by an electronic signature and the RSA 3072 encryption method, and it is not possible to access the contents of the archive without having a private key!
